### ISSUE TITLE
Feature Request: Add ELF support.

### ISSUE THREAD

**Issue by daschewie** [pweingar/FoenixMCP#1]
Please add ELF loader to simplify development. This code might be useful: https://github.com/ProbablyNotArtyom/G-DOS/blob/master/src/elf.c

**Comment by pweingar** [comment]
Thanks, daschewie. My intention is for ELF to be supported in this kernel, since the 68000 compilers all seem to have ELF as a target format.

**Comment by daschewie** [comment]
ELF support was added.
