### ISSUE TITLE
Bug in fsys_findnext

### ISSUE THREAD

**Issue by vinz6751** [pweingar/FoenixMCP#28]
I think that there is a problem in fsys_findnext in fsys.c

line335 is `        fres = f_findnext(&g_dir_state[dir], &finfo);` looks clunky.
It feels that it shoudl be  `g_directory` instead of `g_dir_state` , isn't it ?

**Comment by pweingar** [comment]
Yes, you're correct. g_directory should be used instead of g_dir_state. I think you've already addressed this in a PR?

**Comment by vinz6751** [comment]
Yes it's in the PR 29
