### ISSUE TITLE
Add SEEK_END origin to sys_chan_seek.

### ISSUE THREAD

**Issue by daschewie** [pweingar/FoenixMCP#8]
The `fseek` function in C is implemented using the `sys_chan_seek` system call. Currently sys_chan_seek only supports absolute and cursor relative positioning.

We would like support for EOF relative positioning, like the `SEEK_END` feature of fseek.: https://www.tutorialspoint.com/c_standard_library/c_function_fseek.htm

Example Usage:

fseek(f, -100, SEEK_END); // moves to 100 chars from the end.

**Comment by pweingar** [comment]
That should be doable without too much trouble.

**Comment by pweingar** [comment]
Take a look at issue_8 branch and see if that will meet your needs. I haven't tried it, because this build won't run on my K, but it compiles and shouldn't break anything.

**Comment by daschewie** [comment]
The code in the issue_8 branch looks great, thanks for the quick turn around.

**Comment by daschewie** [comment]
This was merged in pr#10
